[package]
name = "postflop-solver"
version = "0.1.0"
authors = ["Wataru Inariba"]
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
holdem-hand-evaluator = { git = "https://github.com/b-inary/holdem-hand-evaluator" }
num-traits = "0.2.14"
once_cell = "1.9.0"
rayon = "1.5.1"
regex = "1.5.4"

[profile.release]
lto = "thin"
panic = "abort"
