[package]
name = "postflop-solver"
version = "0.1.0"
authors = ["Wataru Inariba"]
edition = "2021"
description = "An open-source postflop solver for Texas hold'em poker"
documentation = "https://b-inary.github.io/postflop_solver/postflop_solver/"
repository = "https://github.com/b-inary/postflop-solver"
license = "AGPL-3.0-or-later"

[dependencies]
holdem-hand-evaluator = { git = "https://github.com/b-inary/holdem-hand-evaluator", optional = true }
num-traits = "0.2.15"
once_cell = "1.12.0"
rayon = { version = "1.5.3", optional = true }
regex = "1.5.6"

[features]
default = ["holdem-hand-evaluator", "rayon"]
custom-alloc = []

[profile.release]
lto = "thin"
panic = "abort"
